### PR TITLE
Add propagation notice

### PR DESCRIPTION
**Pull request by peterge1998**
see https://caddy.community/t/autostart-caddy-with-the-netcup-plugin/21872

### CODE REVIEW

**Comment by francislavoie** [comment]
Thanks! I don't think mentioning `certbot` is relevant, that part can be removed.

**Comment by francislavoie** [comment]
I mean "This may be annoying when calling certbot manually but should not be a problem in automated setups.", this can be removed IMO, or at least reworded to not mention `certbot`. It's not relevant to Caddy.

And I mean the `#28` link, which makes it read like it's a link to an issue in _this_ repo.

**Comment by peterge1998** [comment]
like this?

**Comment by francislavoie** [comment]
Thanks!

**Pull request merged**
